apiVersion: v1
kind: Secret
metadata:
  name: {{ include "styx.fullname" . }}-gcp-key
  labels:
    {{- include "styx.labels" . | nindent 4 }}
type: Opaque
data:
  service-account.json: {{ .Values.gcp.serviceAccountKey | b64enc | quote }} 